### ISSUE TITLE
Server gracefully disconnects clients on connect

### ISSUE THREAD

**Issue by temparus** [chkr1011/MQTTnet#570]
We have a server application that works great with version 2.8.5 (except that we experience the issue #535). This application also includes connections over Websocket.

To get rid of the mentioned issue, we updated to version `3.0.0-alpha2`. Connections from MQTT clients (including clients created with this library) are closed gracefully when connecting. The configured `ConnectionValidator` nor the `OnClientConnected` delegate is never called.

The `OnClientDisconnected` delegate is called instead. The passed client id is empty, which should also not be the case.

Based on the logged error, it seems that there is an issue with detecting the protocol version. The following error is logged:
```
>> [2019-03-07T17:58:35.5086411Z] [13] [MqttHostedServer.MqttServer.MqttClientSessionsManager] [Error]: Protocol version not set or detected.
System.InvalidOperationException: Protocol version not set or detected.
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.ThrowIfFormatterNotSet()
   at MQTTnet.AspNetCore.ReaderExtensions.TryDecode(MqttPacketFormatterAdapter formatter, ReadOnlySequence`1& input, MqttBasePacket& packet, SequencePosition& consumed, SequencePosition& observed)
   at MQTTnet.AspNetCore.MqttConnectionContext.ReceivePacketAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Server.MqttClientSessionsManager.HandleConnectionAsync(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
>> [2019-03-07T17:58:35.5092268Z] [13] [MqttHostedServer.MqttServer.MqttClientSessionsManager] [Verbose]: Session for client '' deleted.
```

I observed exactly the same behavior when creating a broker and a client project from scratch with the 3.0.0-alpha2 version of the library.

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this issue. The WebSocket part is not finished yet for 3.0.0. I will have a look and let you know as soon as this is fixed.

Best regards
Christian

**Comment by temparus** [comment]
Thanks for your fast response and your great work!

Is there any time frame or roadmap for this?

**Comment by chkr1011** [comment]
No roadmap, sorry. But I fixed some things in the latest develop branch. Could you please test with that version?

**Comment by temparus** [comment]
Thanks. Connecting over WebSocket works again. Unfortunately, the behavior is still observed when connecting to the default port. I get the same result with the client version from the develop branch as with version 2.8.5.

The error is still that it could not detect the protocol version.
