### ISSUE TITLE
On Broker side, when setting TLS option , receiving unsupported method exception on Linux x64 Ubuntu 16.04 Mono 5.10

### ISSUE THREAD

**Issue by 41m4n** [chkr1011/MQTTnet#730]
### Describe the bug
On Broker side, when setting TLS option , receiving unsupported method exception on Linux x64 Ubuntu 16.04 Mono 5.10 .NetFramework 4.6.1

### Which project is your bug related to?
- Server

### To Reproduce
1. Using this version of MQTTnet 3.0.5
2. Run this code in server / broker

### Additional context / logging

```
Specified method is not supported.
  at Mono.Btls.X509CertificateImplBtls.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType, System.Byte[] password) [0x00023] in <ccafeb0e74bd436bb84e5138772c2bb0>:0
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType, System.Byte[] password) [0x0000b] in <f56c876907e742b0aa586f051fcce845>:0
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType) [0x00000] in <f56c876907e742b0aa586f051fcce845>:0
```
### Code example
```
var optionsBuilder = new MqttServerOptionsBuilder()
                    .WithoutDefaultEndpoint() 
                    .WithEncryptedEndpoint()
                    .WithEncryptedEndpointPort(mqttServerPort)
                    .WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx))
                    .WithEncryptionSslProtocol(SslProtocols.Tls12);
```

**Comment by SeppPenner** [comment]
This should be working properly in .Net 4.6.1: https://docs.microsoft.com/de-de/dotnet/api/system.security.cryptography.x509certificates.x509certificate.export?view=netframework-4.6.1...

I assume, you're loading your certificate similar to the example under https://github.com/chkr1011/MQTTnet/wiki/Server:

```csharp
var currentPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
var certificate = new X509Certificate2(Path.Combine(currentPath, "certificate.pfx"),"yourPassword", X509KeyStorageFlags.Exportable);
```

**Comment by 41m4n** [comment]
Yes, I loaded the certificate referring to the example in https://github.com/chkr1011/MQTTnet/wiki/Server

but I got the error as to below 
```
Specified method is not supported.
  at Mono.Btls.X509CertificateImplBtls.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType, System.Byte[] password) [0x00023] in <ccafeb0e74bd436bb84e5138772c2bb0>:0
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType, System.Byte[] password) [0x0000b] in <f56c876907e742b0aa586f051fcce845>:0
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (System.Security.Cryptography.X509Certificates.X509ContentType contentType) [0x00000] in <f56c876907e742b0aa586f051fcce845>:0
```

I'm running it on Linux

**Comment by SeppPenner** [comment]
> I'm running it on Linux

I've seen that, but mono should handle that properly...

**Comment by 41m4n** [comment]
Unfortunately, it is still not working. If I want encryption, can you recommend an alternative way to do so. From other resource is that encrypting the message before sending

**Comment by SeppPenner** [comment]
Well, you could try to run it on .NetCore maybe? To be honest, I have never seen .Net Framework running on a Linux machine at all...

**Comment by chkr1011** [comment]
@41m4n So the problem is **not** MQTTnetServer? It is about how to generate proper certificates (which does not work on Linux when using the Wiki examples) right?

**Comment by 41m4n** [comment]
I tried running it on windows environment, the error i mentioned does not appear. But it is better if one can reproduce it just to make sure that i had not done silly mistake in the middle of the code

**Comment by chkr1011** [comment]
I would say that this export function is simply not supported when using Mono and Linux. There is nothing we can do.

**Comment by SeppPenner** [comment]
> I would say that this export function is simply not supported when using Mono and Linux. There is nothing we can do.

At least not in .Net Framework. Maybe in .Net Core?

**Comment by 41m4n** [comment]
```
At least not in .Net Framework. Maybe in .Net Core?
```
For .Net Core i haven't tried because currently i required to use mono. 
```
I would say that this export function is simply not supported when using Mono and Linux. There is nothing we can do.
```
 If that's the case then it's okay. Just wanted to verify my code is correct or wrong
